import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
type Picture = {name:string; width:number; height:number; preview:string};
type Api = {open_image:()=>Promise<Picture|null>; reset:()=>Promise<Picture>; highlight:(width:number)=>Promise<Picture>; save_image:()=>Promise<string|null>};
declare global {interface Window {pywebview?:{api:Api}}}
function App(){
  const [ready,setReady]=useState(!!window.pywebview?.api), [busy,setBusy]=useState(false);
  const [pic,setPic]=useState<Picture|null>(null), [width,setWidth]=useState(''), [zoom,setZoom]=useState('fit');
  const [message,setMessage]=useState('Open an image to get started.'), [error,setError]=useState('');
  useEffect(()=>{const fn=()=>setReady(true);window.addEventListener('pywebviewready',fn);return()=>window.removeEventListener('pywebviewready',fn)},[]);
  async function action(fn:(api:Api)=>Promise<void>){if(!window.pywebview?.api||busy)return;setBusy(true);setError('');try{await fn(window.pywebview.api)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  const open=()=>action(async api=>{const p=await api.open_image();if(p){setPic(p);setWidth(String(p.width));setMessage('Original image loaded.')}});
  const valid=!!pic&&Number.isInteger(Number(width))&&Number(width)>=1&&Number(width)<=pic.width;
  return <div className="app"><header><div className="brand"><span className="mark">▧</span><div><strong>ImageResizer</strong><small>SEAM EXPLORER</small></div></div><div className="toolbar"><button disabled={!ready||busy} onClick={open}>Open image</button><button className="primary" disabled={!pic||busy} onClick={()=>action(async api=>{const path=await api.save_image();if(path)setMessage('Image saved.');})}>Save image ↗</button></div></header>
  <main><section className="workspace"><div className="canvasbar"><span>{pic?.name??'Your workspace'}</span><label>View <select value={zoom} onChange={e=>setZoom(e.target.value)}><option value="fit">Fit to window</option><option value="1">100%</option><option value="0.5">50%</option><option value="0.25">25%</option></select></label></div><div className={'canvas '+(zoom==='fit'?'fit':'actual')} aria-busy={busy}>{pic?<img alt="Image preview" src={pic.preview} style={zoom==='fit'?{}:{width:pic.width*Number(zoom),maxWidth:'none',maxHeight:'none'}}/>:<div className="empty"><span className="emptyicon">▧</span><h1>A new perspective<br/>on your images.</h1><p>Explore the seams that shape an image.<br/>Everything stays on your computer.</p><button className="primary" disabled={!ready||busy} onClick={open}>Choose an image</button><small>PNG · JPEG · WEBP · BMP · TIFF</small></div>}</div></section>
  <aside><div className="eyebrow">IMAGE TOOLS</div><h2>Explore the seams</h2><p className="intro">Preview the vertical seams the current engine would remove.</p><div className="dimensions"><span>Original dimensions</span><strong>{pic?`${pic.width} × ${pic.height}`:'— × —'} <small>px</small></strong></div><label className="field">Target width<div className="inputwrap"><input aria-label="Target width" type="number" min="1" max={pic?.width} value={width} disabled={!pic||busy} onChange={e=>setWidth(e.target.value)}/><span>px</span></div></label><div className="hint">{pic?`Choose between 1 and ${pic.width} pixels.`:'Load an image to set its target width.'}</div><button className="primary full" disabled={!ready||busy||!valid} onClick={()=>action(async api=>{setPic(await api.highlight(Number(width)));setMessage('Seam preview ready. Image dimensions are unchanged.');})}>{busy?'Working…':'Highlight seams'}</button><button className="full quiet" disabled={!pic||busy} onClick={()=>action(async api=>{const p=await api.reset();setPic(p);setWidth(String(p.width));setMessage('Original image restored.');})}>Restore original</button><div className="note"><span className="dot"/> Preview mode<p>This version highlights seams in red. Resizing and height adjustment are not yet available.</p></div></aside></main><footer><span role={error?'alert':'status'} className={error?'error':''}>{error||(!ready?'Connecting to the desktop app…':busy?'Processing image…':message)}</span><span>LOCAL PROCESSING</span></footer></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
